name             'prozziebootstrap'
maintainer       'Wizzie Analytics'
maintainer_email 'devel@wizzie.io'
license          'All rights reserved'
description      'Bootstraps Prozzie Marketplace AMI'
version          '0.0.1'
