name             'prozzieprov'
maintainer       'Wizzie Analytics'
maintainer_email 'devel@wizzie.io'
license          'All rights reserved'
description      'Provision Prozzie Marketplace AMI'
version          '0.0.1'
